# Generated by Django 3.1.5 on 2021-07-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBDD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='Nombre',
            field=models.CharField(max_length=150),
        ),
    ]
