# Generated by Django 3.1.5 on 2021-07-26 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BBDD', '0002_auto_20210725_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histpago',
            name='Pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BBDD.tipopago'),
        ),
    ]
