# Generated by Django 3.1.5 on 2021-12-06 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BBDD', '0003_auto_20210725_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='histpago',
            name='Alumno',
        ),
    ]
