# Generated by Django 3.1.5 on 2021-12-06 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BBDD', '0004_remove_histpago_alumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='histpago',
            name='Alumno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BBDD.alumno'),
        ),
    ]
